# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
