# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 09:06
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
