# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20191021_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
